import type { CollectionConfig } from '../types'
const adminOnly = ({ req }: { req: { user?: unknown } }) => Boolean(req.user)
const publishedOrAdmin = ({ req }: { req: { user?: unknown } }) => req.user ? true : { status: { equals: 'published' } }
const localizedText = (name: string, required = true) => ({ name, type:'group' as const, fields:[{name:'en',type:'text' as const,required},{name:'ar',type:'text' as const,required}] })
const localizedTextarea = (name: string) => ({ name, type:'group' as const, fields:[{name:'en',type:'textarea' as const},{name:'ar',type:'textarea' as const}] })
const baseAccess = { read: publishedOrAdmin, create: adminOnly, update: adminOnly, delete: adminOnly }
export const Services: CollectionConfig = { slug:'services', access:baseAccess, admin:{useAsTitle:'slug'}, fields:[{name:'slug',type:'text',required:true,unique:true}, localizedText('title'), localizedTextarea('description'), localizedText('statusLabel',false), {name:'icon',type:'text'}, {name:'status',type:'select',defaultValue:'published',options:['draft','published']}] }
export const Projects: CollectionConfig = { slug:'projects', access:baseAccess, admin:{useAsTitle:'slug'}, fields:[{name:'slug',type:'text',required:true,unique:true}, localizedText('title'), localizedTextarea('summary'), localizedTextarea('problem'), localizedTextarea('solution'), localizedTextarea('result'), {name:'technologies',type:'array',fields:[{name:'name',type:'text'}]}, {name:'externalLink',type:'text'}, {name:'seoTitle',type:'text'}, {name:'seoDescription',type:'textarea'}, {name:'status',type:'select',defaultValue:'published',options:['draft','published']}] }
export const Courses: CollectionConfig = { slug:'courses', access:baseAccess, admin:{useAsTitle:'slug'}, fields:[{name:'slug',type:'text',required:true,unique:true}, localizedText('title'), localizedTextarea('description'), localizedText('statusLabel',false), {name:'status',type:'select',defaultValue:'published',options:['draft','published']}] }
export const Testimonials: CollectionConfig = { slug:'testimonials', access:baseAccess, admin:{useAsTitle:'name'}, fields:[{name:'name',type:'text',required:true},{name:'role',type:'text'}, localizedTextarea('message'), {name:'rating',type:'number',min:1,max:5}, {name:'status',type:'select',defaultValue:'published',options:['draft','published']}] }
export const FAQs: CollectionConfig = { slug:'faqs', access:baseAccess, admin:{useAsTitle:'order'}, fields:[{name:'order',type:'number'}, localizedText('question'), localizedTextarea('answer'), {name:'status',type:'select',defaultValue:'published',options:['draft','published']}] }
export const ContactSubmissions: CollectionConfig = { slug:'contact-submissions', access:{read:adminOnly,create:()=>true,update:adminOnly,delete:adminOnly}, fields:[{name:'name',type:'text'},{name:'email',type:'email'},{name:'phone',type:'text'},{name:'service',type:'text'},{name:'budget',type:'text'},{name:'message',type:'textarea'},{name:'language',type:'select',options:['en','ar']}] }
export const CourseInterestLeads: CollectionConfig = { slug:'course-interest-leads', access:{read:adminOnly,create:()=>true,update:adminOnly,delete:adminOnly}, fields:[{name:'name',type:'text'},{name:'email',type:'email'},{name:'course',type:'text'},{name:'message',type:'textarea'},{name:'language',type:'select',options:['en','ar']}] }
