import { ArrowRight, CheckCircle2, Code2, Compass, GraduationCap, PanelsTopLeft, Sparkles, Workflow } from 'lucide-react'
import { ButtonLink } from '@/components/ui/button'
import { BookingLink, ServiceLink } from '@/components/site/tracked-links'
import { ContactForm } from '@/components/forms/contact-form'
import { CourseInterestForm } from '@/components/forms/course-interest-form'
import { FadeIn } from '@/components/site/motion'
import { courses, faqs, Locale, localePath, projects, services } from '@/lib/i18n'

const iconMap = { Compass, Code2, Workflow, Sparkles, PanelsTopLeft, GraduationCap }
export function HomePage({ locale }: { locale: Locale }) { const ar=locale==='ar'; const cal=process.env.NEXT_PUBLIC_CAL_LINK; return <main>
 <section className="section pt-10"><div className="container grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><FadeIn><p className="eyebrow">{ar?'استشارات تقنية وتطوير ويب':'Software engineering · consulting · automation'}</p><h1 className="mt-4 text-4xl font-black leading-tight tracking-[-.04em] sm:text-6xl">{ar?'أبني حلولاً رقمية ذكية تحوّل الأفكار إلى أنظمة عملية، سريعة، وقابلة للتوسع.':'I build smart digital solutions that turn ideas into fast, practical, and scalable systems.'}</h1><p className="mt-6 max-w-2xl text-lg leading-8 muted">{ar?'محمد العريبي مهندس برمجيات ومستشار تقني يساعد الأفراد والشركات الصغيرة على بناء مواقع وتطبيقات وأتمتة وتدفقات عمل مدعومة بالذكاء الاصطناعي بوضوح واحترافية.':'Mohammed Al Oraibi is a software engineer and technical consultant helping individuals and small businesses build websites, automations, AI workflows, and scalable digital systems with clarity.'}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row">{cal?<BookingLink href={cal} className="btn btn-primary">{ar?'احجز استشارة':'Book a Consultation'} <ArrowRight size={18}/></BookingLink>:<ButtonLink href={localePath(locale,'/contact')}>{ar?'اطلب استشارة':'Request a Consultation'}</ButtonLink>}<ButtonLink href={localePath(locale,'/services')} variant="secondary">{ar?'استعرض الخدمات':'View Services'}</ButtonLink></div><div className="mt-8 grid gap-3 text-sm font-semibold sm:grid-cols-3"><span><CheckCircle2 size={18}/> {ar?'جوال أولاً':'Mobile-first'}</span><span><CheckCircle2 size={18}/> {ar?'قابل للتوسع':'Scalable'}</span><span><CheckCircle2 size={18}/> {ar?'ثنائي اللغة':'Bilingual'}</span></div></FadeIn><FadeIn className="card p-5"><div className="rounded-[24px] bg-[#111827] p-5 text-white"><div className="grid gap-4"><div className="rounded-2xl bg-white/10 p-4"><p className="text-sm text-gray-300">{ar?'نظام استشارة':'Consulting system'}</p><p className="mt-2 text-2xl font-black">Strategy → Build → Automate</p></div><div className="grid grid-cols-2 gap-3">{['SEO','AI','Web','Ops'].map(x=><div key={x} className="rounded-2xl bg-white/10 p-4 font-bold">{x}</div>)}</div><div className="rounded-2xl border border-white/10 p-4 text-sm text-gray-300">{ar?'تصميم نظيف، محتوى واضح، وبنية تقنية قابلة للفهرسة والقياس.':'Clean design, clear content, and technical architecture that is crawlable, measurable, and maintainable.'}</div></div></div></FadeIn></div></section>
 <Section eyebrow={ar?'عن محمد':'About'} title={ar?'خبرة تقنية مبسطة وواضحة':'Clear technical expertise without unnecessary complexity'}><p className="max-w-3xl text-lg leading-8 muted">{ar?'يركز محمد على تحويل الاحتياجات العملية إلى حلول رقمية منظمة: مواقع سريعة، أنظمة أتمتة، استشارات تقنية، وتدفقات عمل ذكية. هدفه مساعدة العميل على فهم الخيارات التقنية واتخاذ قرار صحيح قبل التنفيذ.':'Mohammed focuses on turning practical needs into organized digital solutions: fast websites, automation systems, technical consulting, and intelligent workflows. The goal is to help clients understand options and choose the right path before implementation.'}</p></Section>
 <Section eyebrow={ar?'الخدمات':'Services'} title={ar?'خدمات تقنية قابلة للتنفيذ والقياس':'Practical technical services designed for outcomes'}><div className="grid-auto">{services.map(s=>{ const Icon=iconMap[s.icon]; const href=s.slug==='personal-brand-websites'||s.slug==='training'?localePath(locale,'/services'):localePath(locale,`/services/${s.slug}`); return <article className="card p-5" key={s.slug}><Icon className="text-[#9b641f]"/><h3 className="mt-4 text-xl font-black">{s.title[locale]}</h3><p className="mt-3 leading-7 muted">{s.short[locale]}</p><p className="mt-4 text-sm font-bold text-[#0f766e]">{s.status[locale]}</p><ServiceLink href={href} service={s.slug} className="mt-5 inline-flex font-bold text-[#7a4b18]">{ar?'اعرف المزيد':'Learn more'} →</ServiceLink></article>})}</div></Section>
 <Section eyebrow={ar?'الحلول':'Solutions'} title={ar?'المشكلات التي يمكن حلها':'Problems Mohammed helps solve'}><div className="grid-auto">{(ar?['تحويل الأفكار إلى أنظمة عاملة','أتمتة العمل المتكرر','تحسين الحضور الرقمي','تبسيط تعلم البرمجة','بناء مواقع سريعة وقابلة للتوسع','اختيار الأدوات والمعمارية المناسبة']:['Turning ideas into working systems','Automating repetitive work','Improving digital presence','Helping beginners understand technology','Building fast and scalable websites','Choosing the right tools and architecture']).map(x=><div className="card p-5 font-bold" key={x}>{x}</div>)}</div></Section>
 <Section eyebrow={ar?'دراسات حالة':'Case studies'} title={ar?'نماذج مشاريع قابلة للتحرير من نظام إدارة المحتوى':'CMS-editable project and case study examples'}><div className="grid-auto">{projects.map(p=><article className="card p-5" key={p.slug}><h3 className="text-xl font-black">{p.title[locale]}</h3><p className="mt-3 leading-7 muted">{p.summary[locale]}</p><div className="mt-4 flex flex-wrap gap-2">{p.tech.map(t=><span className="rounded-full bg-white px-3 py-1 text-xs font-bold" key={t}>{t}</span>)}</div><ButtonLink href={localePath(locale,`/projects/${p.slug}`)} variant="secondary" className="mt-5">{ar?'قراءة الحالة':'Read case study'}</ButtonLink></article>)}</div></Section>
 <Section eyebrow={ar?'الاستشارة':'Consultation'} title={ar?'احجز جلسة واضحة قبل البناء':'Book a clear session before building'}><div className="card flex flex-col justify-between gap-5 p-6 md:flex-row md:items-center"><p className="max-w-2xl leading-8 muted">{ar?'ناقش فكرتك أو مشكلتك التقنية واحصل على اتجاه عملي للخطوات التالية.':'Discuss your idea or technical challenge and leave with a practical direction for next steps.'}</p>{cal?<BookingLink href={cal} className="btn btn-primary">{ar?'افتح رابط الحجز':'Open booking link'}</BookingLink>:<ButtonLink href={localePath(locale,'/contact')}>{ar?'راسلني للحجز':'Contact to book'}</ButtonLink>}</div></Section>
 <Section eyebrow={ar?'الدورات':'Courses'} title={ar?'دورات تقنية مبسطة قيد الإعداد':'Beginner-friendly technical courses are being prepared'}><div className="grid gap-6 lg:grid-cols-2"><div className="grid gap-4">{courses.map(c=><div className="card p-5" key={c.title.en}><h3 className="font-black">{c.title[locale]}</h3><p className="mt-2 muted">{c.description[locale]}</p><p className="mt-3 text-sm font-bold text-[#0f766e]">{c.status[locale]}</p></div>)}</div><CourseInterestForm locale={locale}/></div></Section>
 <Section eyebrow={ar?'آراء العملاء':'Testimonials'} title={ar?'إشارات ثقة قابلة للإدارة من لوحة التحكم':'Trust signals editable from the CMS'}><div className="grid-auto">{(ar?[['عميل تجريبي','صاحب مشروع','شرح محمد الخيارات التقنية بطريقة واضحة وساعدنا على اختيار مسار عملي.'],['متعلم','طالب برمجة','المحتوى كان مبسطاً ومنظماً وسهل التطبيق.']]:[['Pilot client','Founder','Mohammed explained technical options clearly and helped us choose a practical path.'],['Learner','Programming student','The content was simple, structured, and easy to apply.']]).map(t=><blockquote className="card p-5" key={t[0]}><p className="leading-7">“{t[2]}”</p><footer className="mt-4 text-sm font-bold">{t[0]} · <span className="muted">{t[1]}</span></footer></blockquote>)}</div></Section>
 <Section eyebrow={ar?'أسئلة شائعة':'FAQ'} title={ar?'إجابات مباشرة للزوار ومحركات الإجابة':'Direct answers for visitors and answer engines'}><div className="grid gap-3">{faqs[locale].map(([q,a])=><details className="card p-5" key={q}><summary className="cursor-pointer font-black">{q}</summary><p className="mt-3 leading-7 muted">{a}</p></details>)}</div></Section>
 <Section eyebrow={ar?'تواصل':'Contact'} title={ar?'أخبرني بما تريد بناءه':'Tell me what you want to build'}><ContactForm locale={locale}/></Section>
 </main> }
function Section({ eyebrow, title, children }: { eyebrow:string; title:string; children:React.ReactNode }) { return <section className="section"><div className="container"><FadeIn><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 max-w-3xl text-3xl font-black tracking-[-.03em] sm:text-5xl">{title}</h2><div className="mt-8">{children}</div></FadeIn></div></section> }
