import { Header, Footer } from './layout'
import { ButtonLink } from '@/components/ui/button'
import { ContactForm } from '@/components/forms/contact-form'
import { CourseInterestForm } from '@/components/forms/course-interest-form'
import { Locale, localePath, services, projects, courses, faqs } from '@/lib/i18n'
import { ProjectTrack } from './tracked-links'

export function ServicesPage({ locale }: { locale: Locale }) { const ar=locale==='ar'; return <Shell locale={locale}><section className="section"><div className="container"><p className="eyebrow">{ar?'الخدمات':'Services'}</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{ar?'خدمات رقمية واضحة وقابلة للتنفيذ':'Clear digital services for practical outcomes'}</h1><p className="mt-5 max-w-3xl text-lg leading-8 muted">{ar?'اختر خدمة مستقلة أو ابدأ باستشارة لتحديد الخطة المناسبة.':'Choose a focused service or start with a consultation to define the right plan.'}</p><div className="mt-10 grid-auto">{services.map(s=><article className="card p-5" key={s.slug}><h2 className="text-xl font-black">{s.title[locale]}</h2><p className="mt-3 leading-7 muted">{s.short[locale]}</p><p className="mt-3 text-sm font-bold text-[#0f766e]">{s.status[locale]}</p>{['technical-consulting','web-development','automation','ai-workflows'].includes(s.slug)?<ButtonLink href={localePath(locale,`/services/${s.slug}`)} className="mt-5" variant="secondary">{ar?'تفاصيل الخدمة':'Service details'}</ButtonLink>:null}</article>)}</div></div></section></Shell> }
export function ServiceDetailPage({ locale, slug }: { locale: Locale; slug: string }) { const ar=locale==='ar'; const s=services.find(x=>x.slug===slug)!; return <Shell locale={locale}><section className="section"><div className="container"><p className="eyebrow">{ar?'خدمة':'Service'}</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{s.title[locale]}</h1><p className="mt-6 max-w-3xl text-lg leading-8 muted">{s.details[locale]}</p><div className="mt-10 grid gap-5 md:grid-cols-3"><div className="card p-5"><h2 className="font-black">{ar?'مناسب لـ':'Best for'}</h2><p className="mt-3 muted">{ar?'الأفراد والشركات الصغيرة وصناع المحتوى الذين يحتاجون خطة تقنية واضحة.':'Individuals, small businesses, and creators who need a clear technical plan.'}</p></div><div className="card p-5"><h2 className="font-black">{ar?'المخرجات':'Deliverables'}</h2><p className="mt-3 muted">{ar?'توصيات عملية، خطوات تنفيذ، وأولويات واضحة.':'Practical recommendations, implementation steps, and clear priorities.'}</p></div><div className="card p-5"><h2 className="font-black">{ar?'الخطوة التالية':'Next step'}</h2><p className="mt-3 muted">{ar?'احجز استشارة أو أرسل تفاصيل مشروعك.':'Book a consultation or send project details.'}</p></div></div><ButtonLink href={localePath(locale,'/contact')} className="mt-8">{ar?'ابدأ الآن':'Start now'}</ButtonLink></div></section></Shell> }
export function ProjectsPage({ locale }: { locale: Locale }) { const ar=locale==='ar'; return <Shell locale={locale}><section className="section"><div className="container"><p className="eyebrow">{ar?'المشاريع':'Projects'}</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{ar?'دراسات حالة ومشاريع':'Projects and case studies'}</h1><div className="mt-10 grid-auto">{projects.map(p=><article className="card p-5" key={p.slug}><h2 className="text-xl font-black">{p.title[locale]}</h2><p className="mt-3 muted">{p.summary[locale]}</p><ButtonLink href={localePath(locale,`/projects/${p.slug}`)} className="mt-5" variant="secondary">{ar?'قراءة المزيد':'Read more'}</ButtonLink></article>)}</div></div></section></Shell> }
export function ProjectDetailPage({ locale, slug }: { locale: Locale; slug: string }) { const ar=locale==='ar'; const p=projects.find(x=>x.slug===slug) || projects[0]; return <Shell locale={locale}><ProjectTrack slug={slug}/><article className="section"><div className="container"><p className="eyebrow">{ar?'دراسة حالة':'Case study'}</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{p.title[locale]}</h1><p className="mt-6 max-w-3xl text-lg leading-8 muted">{p.summary[locale]}</p><div className="mt-10 grid gap-5"><Block title={ar?'المشكلة':'Problem'} body={p.problem[locale]}/><Block title={ar?'الحل':'Solution'} body={p.solution[locale]}/><Block title={ar?'النتيجة':'Result'} body={p.result[locale]}/></div><div className="mt-6 flex flex-wrap gap-2">{p.tech.map(t=><span key={t} className="rounded-full bg-white px-3 py-1 text-sm font-bold">{t}</span>)}</div></div></article></Shell> }
export function CoursesPage({ locale }: { locale: Locale }) { const ar=locale==='ar'; return <Shell locale={locale}><section className="section"><div className="container grid gap-8 lg:grid-cols-[1fr_.8fr]"><div><p className="eyebrow">{ar?'الدورات':'Courses'}</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{ar?'سجّل اهتمامك بالدورات القادمة':'Register interest in upcoming courses'}</h1><div className="mt-8 grid gap-4">{courses.map(c=><div className="card p-5" key={c.title.en}><h2 className="font-black">{c.title[locale]}</h2><p className="mt-2 muted">{c.description[locale]}</p></div>)}</div></div><CourseInterestForm locale={locale}/></div></section></Shell> }
export function ContactPage({ locale }: { locale: Locale }) { const ar=locale==='ar'; return <Shell locale={locale}><section className="section"><div className="container grid gap-8 lg:grid-cols-[.8fr_1fr]"><div><p className="eyebrow">{ar?'تواصل':'Contact'}</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{ar?'ابدأ المحادثة':'Start the conversation'}</h1><p className="mt-5 leading-8 muted">{ar?'أرسل تفاصيل فكرتك أو التحدي التقني وسأرد بخطوة مناسبة.':'Send your idea or technical challenge and I will respond with a suitable next step.'}</p></div><ContactForm locale={locale}/></div></section></Shell> }
export function PrivacyPage({ locale }: { locale: Locale }) { const ar=locale==='ar'; return <Shell locale={locale}><section className="section"><div className="container max-w-3xl"><h1 className="text-4xl font-black">{ar?'سياسة الخصوصية':'Privacy Policy'}</h1><div className="mt-6 space-y-4 leading-8 muted"><p>{ar?'نجمع المعلومات التي ترسلها طوعاً عبر نماذج التواصل أو تسجيل الاهتمام فقط.':'We collect only the information you voluntarily submit through contact and course interest forms.'}</p><p>{ar?'قد نستخدم تحليلات خصوصية لتحسين تجربة الموقع عند تفعيل معرّفات التحليلات.':'Privacy-friendly analytics may be used to improve the website when analytics IDs are configured.'}</p><p>{ar?'لا نبيع بياناتك. يمكن طلب حذف معلوماتك عبر البريد الإلكتروني المنشور في الموقع.':'We do not sell your data. You can request deletion through the public email listed on this website.'}</p></div></div></section></Shell> }
export function FAQBlock({ locale }: { locale: Locale }) { return <>{faqs[locale].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</> }
function Shell({ locale, children }: { locale: Locale; children: React.ReactNode }) { return <>{locale==='ar'?<div dir="rtl" lang="ar"><Header locale={locale}/>{children}<Footer locale={locale}/></div>:<><Header locale={locale}/>{children}<Footer locale={locale}/></>}</> }
function Block({ title, body }: { title:string; body:string }) { return <section className="card p-6"><h2 className="text-2xl font-black">{title}</h2><p className="mt-3 leading-8 muted">{body}</p></section> }
